FROM almalinux
RUN yum install nginx -y
CMD [ "nginx","-g","daemon off;" ]
LABEL AUTHOR="nagarjuna"\
      PURPOSE="learning docker"\
      DURATION="25hr"
ENV AUTHOR="nagarjuna"\
      PURPOSE="learning docker"\
      DURATION="25hr"
EXPOSE 8080/tcp
